---
- name: Start 'changedetection'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'changedetection'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/changedetection/data'
