---
imch_app_port: 2283

imch_app_version: v1.142.0
imch_valkey_version: 8.1.3-bookworm
imch_postgres_version: 14-vectorchord0.4.3-pgvectors0.2.0@sha256:8d292bdb796aa58bbbaa47fe971c8516f6f57d6a47e7172e62754feb6ed4e7b0

imch_db_password: placeholder
