---
imch_app_port: 2283

imch_app_version: v2.5.6
imch_valkey_version: 9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
imch_postgres_version: 14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23

imch_db_password: placeholder
