---
bkrs_app_port: 9898
bkrs_version: 'v1.10.1'

bkrs_repo_password: placeholder

bkrs_b2:
  s3_access_key_id: placeholder
  s3_secret_access_key: placeholder
  bucket_name: placeholder

bkrs_rclone_config:
  mailru:
    backup_path: placeholder
    webdav_url: placeholder
    user: placeholder
    password_enc: placeholder
  gdrive:
    token_json: placeholder # run `rclone authorize "drive"` on machine with browser to get the json with token
